name: deploy

on:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11.0, windows-2019]
        include:
        - os: macos-11.0
          artifactName: 'electron-vue-demo-0.1.0.dmg'
        - os: windows-2019
          artifactName: 'electron-vue-demo-0.1.0.exe'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: install depenencies
      run: npm install
    - name: lint
      run: npm run lint
    - name: test
      run: npm test
    - name: build
      run: npm run electron:build
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ./dist_electron/${{ matrix.artifactName }}
